<?php

namespace Tests\Browser;

use App\Profile;
use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Browser;
use Tests\Browser\Pages\LoginPage;
use Tests\DuskTestCase;

class LoginTest extends DuskTestCase
{
    use DatabaseMigrations;

    protected $user;

    public function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub
        //creating user and profile
        $userID = 'user_id' . rand();
        $user = factory(User::class)->create(['id' => $userID,'password'=>bcrypt('12345')]);
        $profile = factory(Profile::class)->create(['user_id' => $userID]);
        $this->user = $user;
    }


    public function test_user_can_login_then_logout()
    {
        $user=$this->user;
        $this->browse(function (Browser $browser) use($user) {
            $browser->visit(New LoginPage($user))
                ->screenshot('/login/1.login-page')
                ->fillLoginCredentials()
                ->screenshot('/login/2.fill-info-login-page')
                ->clickLogin()
                ->screenshot('/login/3.logged-into_home_page')
                ->clickLogout()
                ->screenshot('/login/4.logged-out')
                ->storeSource('login_page_source');
        });
    }


}
